---
# tasks file for redis
- name: Install redis
  become: yes
  become_user: root
  apt:
    name: redis
    state: present

- name: Set redis configuration
  become: yes
  become_user: root
  template:
    src: redis.conf
    dest: /etc/redis/redis.conf
    mode: 0755

- name: Restart redis
  become: yes
  become_user: root
  service:
    name: redis
    state: started
    enabled: yes
