---
# tasks file for redis
- name: Install redis
  become: yes
  become_user: root
  apt:
    name: redis
    state: present

- name: Set redis configuration
  become: yes
  become_user: root
  shell: |
    cd /etc/redis
    printf "\n\nbind 0.0.0.0" >> redis.conf
  when: production == true

- name: is redis already running?
  become: yes
  become_user: root
  shell: service redis status warn=false
  register: redis_status
  failed_when: redis_status.rc != 0 and ("unrecognized service" not in redis_status.stderr)
  ignore_errors: true

- name: Restart redis
  become: yes
  become_user: root
  service:
    name: redis
    state: restarted
  when: "redis_status.rc != 0"
