---
# tasks file for nginx
- name: Install Nginx
  become: yes
  become_user: root
  apt:
    name: nginx
    state: present
- name: Extract and setup latest config
  become: yes
  become_user: root
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 755
  notify:
    - Start nginx
