---
# tasks file for nginx
- name: Install Nginx
  become: yes
  become_user: root
  apt:
    name: nginx
    state: present
- name: Create folder for OAE nginx configuration
  become: yes
  become_user: root
  file:
    path: /etc/nginx/oae.conf.d
    state: directory
    owner: oae
    group: oae
- name: Copy the admin nginx configuration
  become: yes
  become_user: root
  template:
    src: nginx.conf
    dest: /etc/nginx/oae.conf.d/admin.vhost.conf
    mode: 0755
- name: Copy the oae nginx configuration
  become: yes
  become_user: root
  template:
    src: nginx.conf
    dest: /etc/nginx/oae.conf.d/oae.vhost.conf
    mode: 0755
- name: Copy the main nginx configuration
  become: yes
  become_user: root
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 0755
  notify:
    - Reload nginx
