---
# tasks file for nginx
- name: Install Nginx
  become: yes
  become_user: root
  apt:
    name: nginx
    state: present
- name: Copy the admin nginx configuration
  become: yes
  become_user: root
  template:
    src: nginx.conf
    dest: /etc/nginx/admin.vhost.conf
    mode: 755
- name: Copy the oae nginx configuration
  become: yes
  become_user: root
  template:
    src: nginx.conf
    dest: /etc/nginx/oae.vhost.conf
    mode: 755
- name: Copy the main nginx configuration
  become: yes
  become_user: root
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 755
  notify:
    - Reload nginx
