- hosts: experimental-db
  roles:
    - cassandra
  tags:
    - cassandra

- hosts: experimental-etherpad
  roles:
    - node
    - etherpad
  tags:
    - etherpad

- hosts: experimental-cache
  roles:
    - redis
  tags:
    - redis

- hosts: experimental-search
  roles:
    - elasticsearch
  tags:
    - elasticsearch

- hosts: experimental-app
  roles:
    - node
    - hilary_setup
  tags:
    - app

  remote_user: oae

- hosts: experimental-web
  roles:
    - nginx
  tags:
    - nginx
