---
- name: Add cassandra apt key
  become: yes
  become_user: root
  apt_key:
    url: https://www.apache.org/dist/cassandra/KEYS
    id: A278B781FE4B2BDA
    state: present
  register: add_repository_key
  ignore_errors: "{{ cassandra_apt_ignore_key_error }}"

- name: Add cassandra repository
  become: yes
  become_user: root
  apt_repository:
    repo: "{{ cassandra_apt_repository }}"
    state: present
    update_cache: true

- name: Install cassandra
  become: yes
  become_user: root
  apt:
    name: cassandra
    state: present

- name: Copy the cassandra.yaml configuration file
  become: yes
  become_user: root
  template:
    src: cassandra.yaml
    dest: /etc/cassandra/cassandra.yaml
    mode: 0755

- name: Checking whether is cassandra already running?
  become: yes
  become_user: root
  shell: service cassandra status warn=false
  register: cassandra_status
  failed_when: cassandra_status.rc != 0 and ("unrecognized service" not in cassandra_status.stderr)
  ignore_errors: true

- name: Restart cassandra
  become: yes
  become_user: root
  service:
    name: cassandra
    state: restarted
  when: "cassandra_status.rc != 0"
