---
# tasks file for cassandra
- name: Download cassandra
  get_url:
    url: http://apache.claz.org/cassandra/2.1.20/apache-cassandra-2.1.20-bin.tar.gz
    dest: /home/oae
  when: first_run == "true"
- name: Unarchive cassandra
  unarchive:
    remote_src: yes
    src: /home/oae/apache-cassandra-2.1.20-bin.tar.gz
    dest: /home/oae
  when: first_run == "true"
- name: Install cassandra
  become: yes
  become_user: root
  shell: |
    mv apache-cassandra-2.1.20 /usr/local/cassandra
    useradd cassandra
    groupadd cassandra
    usermod -aG cassandra cassandra
    chown root:cassandra -R /usr/local/cassandra/
    chmod g+w -R /usr/local/cassandra/
  when: first_run == "true"
- name: Create cassandra service
  become: yes
  become_user: root
  copy:
    dest: /etc/systemd/system/
    src: cassandra.service
    mode: 0755
  when: first_run == "true"

- name: is cassandra already running?
  become: yes
  become_user: root
  shell: service cassandra status warn=false
  register: cassandra_status
  failed_when: cassandra_status.rc != 0 and ("unrecognized service" not in cassandra_status.stderr)
  ignore_errors: true
- name: Restart cassandra
  become: yes
  become_user: root
  service:
    name: cassandra
    state: restarted
  when: "cassandra_status.rc != 0"