---
# tasks file for rabbitmq
- name: Install rabbitmq
  become: yes
  become_user: root
  apt:
    name: rabbitmq-server
    state: present

- name: is rabbitmq-server already running?
  become: yes
  become_user: root
  shell: service rabbitmq-server status warn=false
  register: rabbitmq_status
  failed_when: rabbitmq_status.rc != 0 and ("unrecognized service" not in rabbitmq_status.stderr)
  ignore_errors: true
- name: Restart rabbitmq-server
  become: yes
  become_user: root
  service:
    name: rabbitmq-server
    state: restarted
  when: "rabbitmq_status.rc != 0"