---
# tasks file for rabbitmq
- name: Install rabbitmq
  become: yes
  become_user: root
  apt:
    name: rabbitmq-server
    state: present

- name: Set rabbitmq configuration
  become: yes
  become_user: root
  template:
    src: rabbitmq.config
    dest: /etc/rabbitmq/rabbitmq.config
    mode: 0755

- name: Restart rabbitmq-server
  become: yes
  become_user: root
  service:
    name: rabbitmq-server
    state: restarted
    enabled: yes
