---
- name: Install Client nfs
  become: yes
  become_user: root
  apt:
    name:
      - nfs-common
    state: present
    update_cache: true

- name: Create files folder Hilary
  become: yes
  become_user: root
  file:
    path: /opt/files
    state: directory
    owner: "{{ hilary_user }}"
    group: "{{ hilary_user }}"

- name: Configure /etc/fstab on clients
  become: yes
  become_user: root
  shell: |
    echo "{{ nfs_server }}:/opt/files /opt/files nfs defaults 0 2" >> /etc/fstab
    mount -all
  when: "create_nfs_mount == true"
