---
# tasks file for etherpad
- name: Create etherpad group
  become: yes
  become_user: root
  group:
    name: etherpad
    state: present

- name: Create etherpad user
  become: yes
  become_user: root
  user:
    name: etherpad
    groups: # Empty by default, here we give it some groups
      - etherpad
    state: present

- name: Install etherpad system dependencies
  become: yes
  become_user: root
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - build-essential
      - checkinstall
      - libreadline-gplv2-dev
      - libncursesw5-dev
      - libssl-dev
      - libsqlite3-dev
      - tk-dev
      - libgdbm-dev
      - libc6-dev
      - libbz2-dev
    state: present

- name: Create etherpad root folder
  become: yes
  become_user: root
  file:
    path: "/opt"
    state: directory
    owner: oae
    group: oae

- name: Create etherpad dir
  become: yes
  become_user: root
  file:
    path: "{{ etherpad_path }}"
    state: directory
    owner: oae
    group: oae

- name: Create etherpad log dir
  become: yes
  become_user: root
  file:
    path: "{{ etherpad_path_log }}"
    state: directory
    owner: oae
    group: oae

- name: Check if etherpad has been installed
  stat:
    path: "/etc/systemd/system/etherpad.service"
  register: etherpad_installed

- name: Download etherpad
  get_url:
    url: https://github.com/ether/etherpad-lite/archive/{{ etherpad_version }}.tar.gz
    dest: /home/oae/
  when: etherpad_installed.stat.exists == false

- name: Unarchive etherpad
  unarchive:
    list_files: yes
    remote_src: yes
    src: /home/oae/etherpad-lite-{{ etherpad_version }}.tar.gz
    dest: /home/oae
  when: etherpad_installed.stat.exists == false

- name: Set up etherpad
  become: yes
  become_user: root
  shell: |
    mv /home/oae/etherpad-lite-{{ etherpad_version }}/* {{ etherpad_path }}
    # sed -i -e "93 s,grep.*,grep -E -o 'v[0-9]\.[0-9](\.[0-9])?')," {{ etherpad_path }}/bin/installDeps.sh
    # sed -i -e '96 s,if.*,if [ "${VERSION#v}" = "$NEEDED_VERSION" ]; then,' {{ etherpad_path }}/bin/installDeps.sh
    chown oae:oae -R {{ etherpad_path }}
    chmod g+w -R {{ etherpad_path }}
  when: etherpad_installed.stat.exists == false

- name: Install etherpad dependencies
  shell: |
    {{ etherpad_path }}/bin/installDeps.sh
  when: etherpad_installed.stat.exists == false

- name: Copy settings.json file
  template:
    src: settings.json
    dest: /opt/etherpad/settings.json
    mode: 0755
    group: oae
    owner: oae

- name: Install ep_headings module
  shell: |
    cd {{ etherpad_path }}
    npm install ep_headings
  when: etherpad_installed.stat.exists == false

- name: Install ep_comments module
  shell: |
    cd {{ etherpad_path }}
    npm install ep_page_view
    git clone https://github.com/oaeproject/ep_comments.git node_modules/ep_comments_page \
    cd node_modules/ep_comments_page
    npm install
  when: etherpad_installed.stat.exists == false

- name: Etherpad OAE plugin
  shell: |
    cd {{ etherpad_path }}/node_modules
    git clone https://github.com/oaeproject/ep_oae
    cd ep_oae
    npm install
  when: etherpad_installed.stat.exists == false

- name: CSS changes
  shell: |
    rm {{ etherpad_path }}/node_modules/ep_headings/templates/editbarButtons.ejs
    cp {{ etherpad_path }}/node_modules/ep_oae/static/templates/editbarButtons.ejs {{ etherpad_path }}/node_modules/ep_headings/templates/editbarButtons.ejs
    rm {{ etherpad_path }}/src/static/custom/pad.css
    cp {{ etherpad_path }}/node_modules/ep_oae/static/css/pad.css {{ etherpad_path }}/src/static/custom/pad.css
  when: etherpad_installed.stat.exists == false

- name: Install python and pip
  become: yes
  become_user: root
  apt:
    name: python-pip
    state: present

- name: Install cqlsh
  become: yes
  become_user: root
  shell: |
    pip install cqlsh==4.0.1
    pip install thrift==0.9.3
  when: etherpad_installed.stat.exists == false

- name: Initilize keyspace
  shell: |
    echo "CREATE KEYSPACE IF NOT EXISTS \"{{ cassandra_keyspace }}\" WITH replication = {'class': 'SimpleStrategy', 'replication_factor': {{ cassandra_replication_factor }} };" >> {{ etherpad_path }}/init.cql
    cqlsh -f {{ etherpad_path }}/init.cql {{ cassandra_hosts | first }} 9160
  run_once: true

- name: Rebuild APIKEY file
  shell: |
    rm -rf {{ etherpad_path }}/APIKEY.txt
    echo "{{ etherpad_apikey }}" >> {{ etherpad_path }}/APIKEY.txt

- name: Create etherpad service
  become: yes
  become_user: root
  template:
    dest: /etc/systemd/system/
    src: etherpad.service
    mode: 0755
  when: etherpad_installed.stat.exists == false

- name: Restart etherpad
  become: yes
  become_user: root
  service:
    name: etherpad
    state: started
    enabled: true
