---
# tasks file for node
- name: Download PPA
  shell: |
    curl -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh
  when: first_run == "true"
- name: Refresh cache
  become: yes
  become_user: root
  shell: |
    bash nodesource_setup.sh
  when: first_run == "true"
- name: Install nodejs
  become: yes
  become_user: root
  apt:
    name: nodejs
    state: present
  when: first_run == "true"