---
# tasks file for node
- name: Check if node has been installed
  command: node -v
  register: node_installed
  failed_when: node_installed.rc != 0
  ignore_errors: true

- name: Download PPA
  shell: |
    curl -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh
  when: node_installed.rc != 0 or (node_installed.rc == 0 and node_installed.stdout != 'v10.15.0')

- name: Refresh cache
  become: yes
  become_user: root
  shell: |
    bash nodesource_setup.sh
  when: node_installed.rc != 0 or (node_installed.rc == 0 and node_installed.stdout != 'v10.15.0')

- name: Install nodejs
  become: yes
  become_user: root
  apt:
    name: nodejs
    state: present
  when: node_installed.rc != 0 or (node_installed.rc == 0 and node_installed.stdout != 'v10.15.0')