---
# tasks file for elasticsearch
- name: Install system dependencies for elasticsearch
  become: yes
  become_user: root
  apt:
    name:
      - openjdk-11-jre-headless
    state: present
    update_cache: true

- name: Check if elasticsearch has been installed
  become: yes
  become_user: root
  shell: |
    apt list --installed | grep elasticsearch
  register: elastic_installed
  ignore_errors: true

- name: Download elasticsearch
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.9.3-amd64.deb
    dest: /home/oae/
  when: elastic_installed.rc == 1

- name: Install elasticsearch
  become: yes
  become_user: root
  apt:
    deb: elasticsearch-7.9.3-amd64.deb
  when: elastic_installed.rc == 1

- name: Set elasticsearch configuration
  become: yes
  become_user: root
  shell: |
    cd /etc/elasticsearch
    printf "\nnetwork.host: 0.0.0.0" >> elasticsearch.yml
  when: production == true

- name: Restart elasticsearch
  become: yes
  become_user: root
  service:
    name: elasticsearch
    state: started
    enabled: true
