---
# vars file for cassandra
cassandra_apt_ignore_key_error: true
cassandra_apt_repository: "deb http://www.apache.org/dist/cassandra/debian 21x main"

# for production only
cluster_name: Test Cluster
home_path: "/home/oae"
cassandra_keyspace: "oae"
cassandra_replication_factor: 1
