---
- name: Install Server nfs
  become: yes
  become_user: root
  apt:
    name:
      - nfs-kernel-server
    state: present
    update_cache: true

- name: Create folder for files and uploads
  become: yes
  become_user: root
  file:
    path: /opt/files
    state: directory
    owner: "{{ hilary_user }}"
    group: "{{ hilary_user }}"

- name: Create exports file.
  become: yes
  become_user: root
  template:
    dest: /etc/exports
    src: exports.j2
    mode: 0644

- name: Restart NFS server
  become: yes
  become_user: root
  service:
    name: nfs-kernel-server
    state: restarted
